require('dotenv').config();
const path = require('path');
const express = require('express');
const morgan = require('morgan');
const cors = require('cors');
const { engine } = require('express-handlebars');
const db = require('./db');
const indexRouter = require('./routes/index');
const tripsRouter = require('./routes/trips');
const apiTripsRouter = require('./api/trips');
const app = express();
app.use(morgan('dev'));
app.use(express.json());
app.use(cors({ origin: ['http://localhost:4200'] }));
app.engine('hbs', engine({ extname: '.hbs', defaultLayout: 'main', layoutsDir: path.join(__dirname,'views'), partialsDir: path.join(__dirname,'views','partials') }));
app.set('view engine','hbs'); app.set('views', path.join(__dirname,'views'));
app.use(express.static(path.join(__dirname,'public')));
app.use('/', indexRouter); app.use('/trips', tripsRouter); app.use('/api/trips', apiTripsRouter);
app.use((req,res)=>{ if(req.path.startsWith('/api/')) return res.status(404).json({error:'Not Found'}); res.status(404).render('404',{title:'Not Found'}); });
app.use((err,req,res,next)=>{ console.error(err); if(req.path.startsWith('/api/')) return res.status(500).json({error:'Server Error', message: err.message}); res.status(500).render('500',{title:'Server Error', message: err.message}); });
const PORT = process.env.PORT || 3000;
db.connect().then(()=> app.listen(PORT, ()=>console.log(`Travlr server running at http://localhost:${PORT}`))).catch(e=>{ console.error('DB connect failed', e); process.exit(1); });
